# Generated by Django 4.0.6 on 2022-07-24 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay_type', models.CharField(choices=[('MC', 'Motorcycle'), ('PC', 'Car')], default='PC', max_length=2)),
                ('bay_number', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_reserved', models.BooleanField(default=False)),
                ('is_acrod', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Vehicle Bay',
                'verbose_name_plural': 'Vehicle Bays',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='CarPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abn', models.CharField(blank=True, max_length=11)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('website', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car Park',
                'verbose_name_plural': 'Car Parks',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('vehicle_registration', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='vehicle registration')),
                ('customer_name', models.CharField(max_length=50, verbose_name='customer name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bay', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', related_query_name='reservations', to='parking.bay')),
                ('car_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', related_query_name='reservations', to='parking.carpark')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', related_query_name='reservations', to='parking.customer')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='bay',
            name='car_park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bay', related_query_name='bays', to='parking.carpark'),
        ),
    ]
